### ISSUE TITLE
Neues template für Bayreuth

### ISSUE THREAD

**Issue by s10mn** [ktiu/sylgen#17]
[template.docx](https://github.com/ktiu/sylgen/files/5328804/template.docx)

**Comment by ktiu** [comment]
Magst Du noch die neuen Felder (Sprechstudne, Raum, s. Frankfurt) ergänzen?

**Comment by s10mn** [comment]
Ja: [template_bayreuth.docx](https://github.com/ktiu/sylgen/files/6879832/template_bayreuth.docx)

**Comment by ktiu** [comment]
ersetzt
