### ISSUE TITLE
Optionale Felder für einzeltermine

### ISSUE THREAD

**Issue by ktiu** [ktiu/sylgen#3]
ich habe auf meinem Seminarplan letztes semester noch unterschieden in "pflicht"lektüre und erweiterere literatur und quellen, da wäre es vielleicht auch sinnvoll, unter den sitzungen statt nur "sitzungsablauf" was dazu einzutragen (ich hatte sowieso der übersichtlichkeit halber eine tabelle statt einer liste, vielleicht wäre es denkbar, da so varianten anzubieten? also so bei dem generator auf der startseite eine option zu in welcher form man die ausgabe dann haben will - oder wird das dann zu komplex?)

**Comment by ktiu** [comment]
Um das ganze nicht zu überladen, könnte man eine aufklappbare Schaltfläche mit "erweiterten Optionen"machen, wo man dann beispielsweise die Sitzungen in dieser Art pre-populaten kann

**Comment by s10man** [comment]
Ja dafür würde ich plädieren. Ich spiele gerade mit weiteren Dropdown Menus für Institut, Fachbereich plus noch freie Textfelder - das wird damit schon recht unübersichtlich. Das wirkt dann schnell überfordernd.

**Comment by ktiu** [comment]
Implementiert in 21242e1
